
version: 2

models:
  - name: hudi_insert_table
    description: "Hudi insert non-partitioned table with incremental materialization"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


