name: 'dbthudi'
version: '1.0.0'
config-version: 2
profile: 'dbthudi'

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  +file_format: hudi
  dbthudi:
    stage:
      +materialized: table
