name: 'dbtspark'
version: '1.0.0'
config-version: 2

profile: 'dbtspark'

model-paths: [ "models" ]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbtspark:
    example:
      materialized: table
